# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_fp16_gpu: False
enable_modelarts: False
device_target: 'GPU'
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
run_distribute: False
enable_profiling: False

output_path: "./work_dirs"

checkpoint_path: "./checkpoint/"
ckpt_data: 20221010
# checkpoint_file_path: "Unet3d-10-110.ckpt"

# kidney, tumour
best_dice: [90.30, 50]

# ==============================================================================
# Training options
lr: 0.0003

kidney_batch_size: 16
tumour_batch_size: 2
epoch_size: 10
tumour_epoch_size: 600

warmup_step: 150
warmup_ratio: 0.3
num_classes: 2
in_channels: 1
keep_checkpoint_max: 1

# Export options
device_id: 0
ckpt_file: "./checkpoint/Unet3d-10-110.ckpt"
file_name: "unet3d"
file_format: "MINDIR"

# 310 infer options
pre_result_path: "./preprocess_Result"
post_result_path: "./result_Files"

---
# Help description for each configuration
enable_modelarts: "Whether training on modelarts, default: False"
enable_fp16_gpu: "Whether training on gpu with fp16, default: False"
data_url: "Dataset url for obs"
train_url: "Training output url for obs"
checkpoint_url: "The location of checkpoint for obs"
data_path: "Dataset path for local"
output_path: "Training output path for local"
load_path: "The location of checkpoint for obs"
device_target: "Target device type, available: [Ascend, GPU, CPU]"
enable_profiling: "Whether enable profiling while training, default: False"
num_classes: "Class for dataset"
batch_size: "Batch size for training and evaluation"
epoch_size: "Total training epochs."
keep_checkpoint_max: "keep the last keep_checkpoint_max checkpoint"
checkpoint_path: "The location of the checkpoint file."
checkpoint_file_path: "The location of the checkpoint file."
